import { create } from 'zustand';

export type LanguageCode = 'en' | 'hi' | 'pt' | 'ru' | 'zh';

interface LangState {
  currentLang: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    brand_sub: "Digital Public Good",
    tagline: "Civic Infrastructure Intelligence Platform",
    landing_h1: "Bridging citizen needs with national capital expenditure.",
    landing_sub: "Setu AI ingests voice notes, SMS, and WhatsApp reports across multiple languages, synthesizes citizen demand hotspots with spatial AI, and produces explainable, audit-ready infrastructure priorities.",
    citizen_portal: "Citizen Voice Portal",
    citizen_desc: "Speak in local dialect with automatic Whisper transcription, or submit via WhatsApp and SMS without smartphone requirements.",
    official_portal: "Regional Official Command",
    official_desc: "State planners view geospatial clusters fused with demographic vulnerability and asset deficit indices with embedded RAG policy assistance.",
    admin_portal: "National Commission",
    admin_desc: "Federal decision-makers monitor cross-region infrastructure disparity, transition funding states with strict audit logs, and measure physical ground impact.",
    submit_grievance: "Submit Infrastructure Grievance",
    track_grievance: "Track My Grievances & Live Timeline",
    cat_water: "Drinking Water",
    cat_roads: "Roads & Bridges",
    cat_power: "Power & Grid",
    cat_health: "Primary Health",
    cat_schools: "School Buildings",
    cat_sanitation: "Sanitation",
    speak_label: "Speak in Your Dialect (Multilingual Audio Recording)",
    tap_to_speak: "Tap microphone to speak in your local dialect",
    recording_active: "Recording audio... Speak naturally in Marathi / Hindi / English",
    recorded_done: "Spoken Audio Captured (14s) · Transcription Complete",
    submit_btn: "Submit Grievance to SETU Platform →",
    rank_header: "Ranked Capital Works Queue",
    map_legend_urgent: "Urgent Hotspot (Urgency Score > 0.8)",
    map_legend_high: "High Demand Cluster (> 150 Ingests)",
    explainable_formula: "Explainable Priority Formula Breakdown",
    rag_title: "Policy-Alignment Assistant (RAG)",
    rag_query_btn: "Query Policy Corpus (RAG)",
    leaderboard_tab: "Cross-Region Leaderboard & Capital Allocations",
    impact_tab: "Ground Impact Tracker (114 Verified Projects)",
  },
  hi: {
    brand_sub: "डिजिटल पब्लिक गुड",
    tagline: "नागरिक बुनियादी ढांचा आसूचना मंच",
    landing_h1: "नागरिकों की आवाज़ को राष्ट्रीय विकास बजट से जोड़ना।",
    landing_sub: "सेतु एआई आवाज़, एसएमएस और व्हाट्सएप रिपोर्ट को कई भाषाओं में एकीकृत करता है और पारदर्शी बुनियादी ढांचा प्राथमिकताएं तैयार करता है।",
    citizen_portal: "नागरिक आवाज़ पोर्टल",
    citizen_desc: "स्थानीय बोली में बोलें, व्हिस्पर एआई स्वचालित रूप से अनुवाद करेगा; स्मार्टफोन के बिना एसएमएस और व्हाट्सएप से भी दर्ज करें।",
    official_portal: "क्षेत्रीय योजना कमान",
    official_desc: "राज्य योजनाकार स्थानिक क्लस्टर, जनसांख्यिकीय संवेदनशीलता और घाटा सूचकांकों का विश्लेषण करते हैं।",
    admin_portal: "राष्ट्रीय आयोग",
    admin_desc: "केंद्रीय नीति-निर्माता राज्यों के बीच बजट आवंटन की निगरानी करते हैं और वास्तविक जमीनी प्रभाव मापते हैं।",
    submit_grievance: "समस्या दर्ज करें",
    track_grievance: "मेरी शिकायतें और लाइव टाइमलाइन",
    cat_water: "पेयजल आपूर्ति",
    cat_roads: "सड़कें व पुल",
    cat_power: "बिजली ग्रिड",
    cat_health: "प्राथमिक स्वास्थ्य",
    cat_schools: "विद्यालय भवन",
    cat_sanitation: "स्वच्छता व जल निकासी",
    speak_label: "अपनी स्थानीय भाषा में बोलें (आवाज़ रिकॉर्डिंग)",
    tap_to_speak: "अपनी भाषा में बोलने के लिए माइक दबाएं",
    recording_active: "रिकॉर्डिंग चालू है... स्वाभाविक रूप से बोलें",
    recorded_done: "आवाज़ दर्ज (14 सेकंड) · व्हिस्पर अनुवाद पूर्ण",
    submit_btn: "सेतु पोर्टल पर शिकायत दर्ज करें →",
    rank_header: "प्राथमिकता प्राप्त परियोजनाएं",
    map_legend_urgent: "गंभीर हॉटस्पॉट (आपातकालीन > 0.8)",
    map_legend_high: "उच्च मांग हॉटस्पॉट (> 150 शिकायतें)",
    explainable_formula: "पारदर्शी प्राथमिकता सूत्र विश्लेषण",
    rag_title: "नीति संरेखण सहायक (RAG)",
    rag_query_btn: "सरकारी मास्टरप्लान में खोजें (RAG)",
    leaderboard_tab: "क्षेत्रीय तुलना व बजट आवंटन",
    impact_tab: "जमीनी प्रभाव ट्रैकर (114 सत्यापित)",
  },
  pt: {
    brand_sub: "Bem Público Digital (DPG)",
    tagline: "Plataforma de Inteligência em Infraestrutura Cívica",
    landing_h1: "Conectando as necessidades dos cidadãos aos investimentos federais.",
    landing_sub: "O Setu AI recebe relatos por voz, texto, SMS e WhatsApp em múltiplos idiomas, agrupando pontos críticos de demanda pública com IA explicável.",
    citizen_portal: "Portal da Voz Cidadã",
    citizen_desc: "Grave mensagens de voz em seu dialeto local com transcrição Whisper ou envie via WhatsApp sem precisar de smartphone avançado.",
    official_portal: "Comando Regional",
    official_desc: "Planejadores estaduais visualizam clusters geoespaciais com vulnerabilidade demográfica e assistente de políticas públicas.",
    admin_portal: "Comissão Nacional",
    admin_desc: "Decisores federais monitoram disparidades regionais, controlam logs de auditoria e medem o impacto físico real.",
    submit_grievance: "Registrar Demanda Cidadã",
    track_grievance: "Acompanhar Linha do Tempo ao Vivo",
    cat_water: "Água Potável",
    cat_roads: "Estradas e Pontes",
    cat_power: "Energia Elétrica",
    cat_health: "Saúde Básica",
    cat_schools: "Escolas Públicas",
    cat_sanitation: "Saneamento",
    speak_label: "Grave sua voz (Áudio Multilíngue)",
    tap_to_speak: "Clique no microfone para falar",
    recording_active: "Gravando áudio... Fale naturalmente",
    recorded_done: "Áudio capturado (14s) · Transcrição Whisper pronta",
    submit_btn: "Enviar Demanda ao SETU →",
    rank_header: "Fila Priorizada de Obras",
    map_legend_urgent: "Ponto Crítico Urgente (> 0.8)",
    map_legend_high: "Alta Densidade de Demanda (> 150)",
    explainable_formula: "Detalhamento da Fórmula Explicável",
    rag_title: "Assistente de Políticas Públicas (RAG)",
    rag_query_btn: "Consultar Planos Plurianuais (RAG)",
    leaderboard_tab: "Comparativo Regional e Alocações",
    impact_tab: "Rastreador de Impacto Físico",
  },
  ru: {
    brand_sub: "Цифровое общественное благо",
    tagline: "Платформа инфраструктурного планирования",
    landing_h1: "Объединение запросов граждан с национальным планом развития.",
    landing_sub: "Setu AI объединяет голосовые и текстовые сообщения граждан, выявляет критические потребности и формирует проверяемые приоритеты.",
    citizen_portal: "Голос Граждан",
    citizen_desc: "Голосовые заметки с автоматической транскрипцией Whisper или через SMS.",
    official_portal: "Региональное Командование",
    official_desc: "Анализ геопространственных кластеров с демографическими индексами и помощником RAG.",
    admin_portal: "Национальная Комиссия",
    admin_desc: "Мониторинг межрегионального распределения бюджета и проверка реального физического воздействия.",
    submit_grievance: "Подать Запрос",
    track_grievance: "Отслеживание статуса",
    cat_water: "Водоснабжение",
    cat_roads: "Дороги и Мосты",
    cat_power: "Энергоснабжение",
    cat_health: "Здравоохранение",
    cat_schools: "Школьные здания",
    cat_sanitation: "Санитария",
    speak_label: "Запись голосового сообщения",
    tap_to_speak: "Нажмите микрофон для записи",
    recording_active: "Идет запись аудио...",
    recorded_done: "Запись завершена · Транскрипция готова",
    submit_btn: "Отправить запрос в SETU →",
    rank_header: "Рейтинг приоритетных проектов",
    map_legend_urgent: "Срочный очаг (> 0.8)",
    map_legend_high: "Высокая концентрация (> 150)",
    explainable_formula: "Объяснимая формула приоритета",
    rag_title: "Помощник по государственным планам (RAG)",
    rag_query_btn: "Поиск по государственным планам (RAG)",
    leaderboard_tab: "Межрегиональный рейтинг",
    impact_tab: "Трекер реального эффекта",
  },
  zh: {
    brand_sub: "数字公共品 (DPG)",
    tagline: "民生基础设施智能决策系统",
    landing_h1: "架设公民需求与国家基础设施投资规划的坚实桥梁。",
    landing_sub: "Setu AI 支持多语言语音、文字与短信诉求输入，利用空间智能聚类生成需求热点，输出透明可审计的高优先级民生项目工程。",
    citizen_portal: "公民心声平台",
    citizen_desc: "支持方言语音录入与Whisper自动转写，无需智能手机即可通过短信提交。",
    official_portal: "区域规划调度中心",
    official_desc: "地方规划人员查阅融合了人口脆弱度与基础设施缺口的空间需求热点，配备RAG政策助手。",
    admin_portal: "国家规划委员会",
    admin_desc: "国家决策者监督跨区域均衡分配，依托审计日志管理全生命周期并检验实地成效。",
    submit_grievance: "提交民生基础设施诉求",
    track_grievance: "跟踪我的诉求与进展全流程",
    cat_water: "饮水保障",
    cat_roads: "交通路桥",
    cat_power: "电网能源",
    cat_health: "基层医疗",
    cat_schools: "教育校舍",
    cat_sanitation: "污水环卫",
    speak_label: "使用语音直接阐述诉求",
    tap_to_speak: "点击麦克风开始录音",
    recording_active: "正在录音，请清晰陈述...",
    recorded_done: "语音已录制 (14秒) · Whisper 转写完成",
    submit_btn: "提交民生诉求至 SETU 平台 →",
    rank_header: "高优先级民生工程项目库",
    map_legend_urgent: "特急需求热点 (> 0.8)",
    map_legend_high: "高频需求区域 (> 150条)",
    explainable_formula: "可解释优先级综合计算公式",
    rag_title: "政策法规对齐助手 (RAG)",
    rag_query_btn: "检索国家五年规划投资库 (RAG)",
    leaderboard_tab: "跨区域对比与资金分配",
    impact_tab: "实施成效与物理指标跟踪",
  }
};

export const useLangStore = create<LangState>((set, get) => ({
  currentLang: 'en',
  setLanguage: (lang) => set({ currentLang: lang }),
  t: (key) => {
    const lang = get().currentLang;
    return translations[lang]?.[key] || translations['en'][key] || key;
  }
}));
